#!/usr/bin/env bash

die() { echo "$*"; exit 1; }

slug=${PWD##*/}

[[ -f "${slug//-/_}.gd" ]] || die "Error! solution file is missing"
[[ -f "${slug//-/_}_test.gd" ]] || die "Error! test file is missing"

godot --headless -s lib/test_runner.gd -- "$slug" "$PWD" || die "Test runner script failed."
