# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Exceptions 0.1 [list source [file join $dir exceptions.tcl]]
package ifneeded additionalMathFunctions 0.1 [list source [file join $dir mathfunc.tcl]]
package ifneeded controlCommands 0.1 [list source [file join $dir controlCommands.tcl]]
package ifneeded dictGetdef 0.1 [list source [file join $dir dict.tcl]]
package ifneeded set 0.1 [list source [file join $dir set.tcl]]
package ifneeded stack 0.1 [list source [file join $dir stack.tcl]]
